coefficient:
  sentimental_score: 0.55
  triggered_keywords: 0.05
  triggered_topics: 0.05
  text_simplicity_deviation: 0.05
  confidence_factor: 0.05
  clickbait: 0.05
  subjective: 0.05
  call_to_action: 0.05
  repeated_take: 0.05
  repeated_note: 0.05
similarity_threshold : 0.85
average_news_simplicity: 50
tg:
  channel_names:
    - tmp12345678t
    - qwerty98754321
    - pandoras_box_ua