coefficient:
  sentimental_score: 0.088
  triggered_keywords: 2.75
  triggered_topics: 10.9
  text_simplicity_deviation: 0.166
  confidence_factor: 0.6236
  clickbait: 0.0587
  subjective: 5.43
  call_to_action: 0.182
  repeated_take: 1.32
  repeated_note: 0.01094
similarity_threshold : 0.85
average_news_simplicity: 50
tg:
  channel_names:
    - tmp12345678t
    - qwerty98754321
    - pandoras_box_ua